FROM php:8.1-apache

COPY ./simplenote.conf /etc/apache2/sites-available
COPY ./hosts /etc/hosts
RUN a2enmod rewrite

RUN service apache2 restart
WORKDIR /etc/apache2/sites-available
RUN a2ensite simplenote.conf

EXPOSE 80