version: '1'

services:
  web:
    build: ./docker/php
    volumes:
      -./:/var/www/html
    ports:
      -'8000:80'
    environment:
      - VIRTUAL_HOST=simplenote
    depends_on:
      - db
  
  db:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD: jaimelagalette
      - MYSQL_DATABASE: simplenote
      - MYSQL_USER: simplenote
      - MYSQL_PASSWORD: jaimelagalette
    volumes:
      -mysqldata: /var/lib/mysql
    ports:
      -"3306:3306"