FROM php:8.1-apache

ARG DEBIAN_FRONTEND=noninteractive

#updates
RUN apt-get -y update --fix-missing && apt-get upgrade -y && \
apt-get --no-install-recommends install -y apt-utils && \
rm -rf /var/lib/apt/lists/*

#tools
RUN apt-get -y update && \
    apt-get -y --no-install-recommends install nano wget \
dialog \
zlib1g-dev \
libzip-dev \
libicu-dev && \
    apt-get -y --no-install-recommends install --fix-missing apt-utils \
build-essential \
git \
curl \
libonig-dev && \
    apt-get install -y iputils-ping && \
    apt-get -y --no-install-recommends install --fix-missing libcurl4 \
libcurl4-openssl-dev \
zip \
openssl && \
    rm -rf /var/lib/apt/lists/*

#php extensions
RUN docker-php-ext-install pdo_mysql && \
    docker-php-ext-install bcmath && \
    docker-php-ext-install mysqli && \
    docker-php-ext-install curl && \
    docker-php-ext-install zip && \
    docker-php-ext-install -j$(nproc) intl && \
    docker-php-ext-install mbstring && \
    docker-php-ext-install gettext && \
    docker-php-ext-install calendar && \
    docker-php-ext-install exif

RUN mkdir -p /etc/apache2/ssl

RUN a2enmod ssl && a2enmod rewrite

RUN a2enmod rewrite headers

RUN rm -rf /usr/src/*